### ISSUE TITLE
travis configuration

### ISSUE THREAD

**Issue by benaryorg** [brson/error-chain#18]
I just had a look at the travis configuration and I wondered why you're only testing on stable and not beta and nightly.…

You could always add something like

```yaml
matrix:
  allow_failures:
    - rust: nightly
```

[travis docs for that](https://docs.travis-ci.com/user/languages/rust#Choosing-the-Rust-version)
